// Lays out text in the Kiro Braille font as rows of dot-bitmap letters.
// K, I, R and O always come from the original kiro-cli art; every other glyph
// is generated by kiro-font.ts.

import { glyphDefs, rasterize } from '@/lib/kiro-font';
import { kiroLogoLetterGaps, kiroLogoLetters } from '@/lib/kiro-logo';

export interface SplashLetter {
  dots: boolean[][];
  // Blank dot columns after this letter
  gapAfter: number;
}

export type SplashLine = SplashLetter[];

export const SPLASH_MAX_LENGTH = 32;

// Spacing between letters measured on the original logo (I→R, R→O)
const LETTER_GAP = 4;
const WORD_GAP = 14;
// Wrap words once a line gets wider than this many dots (~ two KIRO widths)
const MAX_LINE_DOTS = 240;

// Braille bit → (column, row) inside the cell, per the Unicode dot numbering
const BRAILLE_DOTS: readonly [number, number][] = [
  [0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [0, 3], [1, 3],
];

function brailleToDots(lines: readonly string[]): boolean[][] {
  const cols = Math.max(...lines.map((line) => Array.from(line).length));
  const dots = Array.from({ length: lines.length * 4 }, () => Array<boolean>(cols * 2).fill(false));
  lines.forEach((line, row) => {
    Array.from(line).forEach((char, col) => {
      const bits = char.codePointAt(0)! - 0x2800;
      if (bits <= 0 || bits > 0xff) return;
      BRAILLE_DOTS.forEach(([dx, dy], bit) => {
        if (bits & (1 << bit)) dots[row * 4 + dy][col * 2 + dx] = true;
      });
    });
  });
  return dots;
}

// Drop blank dot columns on both sides so spacing is uniform across glyph sources
function trim(dots: boolean[][]): boolean[][] {
  const used = (x: number) => dots.some((row) => row[x]);
  let start = 0;
  let end = dots[0].length;
  while (start < end && !used(start)) start++;
  while (end > start && !used(end - 1)) end--;
  return dots.map((row) => row.slice(start, end));
}

const originalLetters: Record<string, boolean[][]> = Object.fromEntries(
  ['K', 'I', 'R', 'O'].map((char, i) => [char, brailleToDots(kiroLogoLetters[i])]),
);

const glyphCache = new Map<string, boolean[][]>();

function glyph(char: string): boolean[][] | null {
  if (!glyphCache.has(char)) {
    const dots = originalLetters[char] ?? (glyphDefs[char] ? rasterize(glyphDefs[char]) : null);
    if (!dots) return null;
    glyphCache.set(char, trim(dots));
  }
  return glyphCache.get(char)!;
}

// Uppercase, strip accents (Fabrício → FABRICIO) and drop unsupported chars
export function normalizeSplashText(input: string): string {
  return input
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toUpperCase()
    .split('')
    .filter((char) => char === ' ' || char in glyphDefs || char in originalLetters)
    .join('')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, SPLASH_MAX_LENGTH)
    .trim();
}

// The untouched kiro-cli splash: original letters, original spacing
function defaultSplash(): SplashLine[] {
  return [
    kiroLogoLetters.map((lines, i) => ({
      dots: brailleToDots(lines),
      gapAfter: kiroLogoLetterGaps[i] * 2,
    })),
  ];
}

export function splashLineWidth(line: SplashLine) {
  return line.reduce((sum, l, i) => sum + l.dots[0].length + (i < line.length - 1 ? l.gapAfter : 0), 0);
}

export function layoutSplash(text?: string | null): SplashLine[] {
  const normalized = text ? normalizeSplashText(text) : '';
  if (!normalized) return defaultSplash();

  const words = normalized.split(' ').map((word) =>
    Array.from(word).map((char) => ({ dots: glyph(char)!, gapAfter: LETTER_GAP })),
  );

  const lines: SplashLine[] = [];
  for (const word of words) {
    const current = lines[lines.length - 1];
    if (current && splashLineWidth(current) + WORD_GAP + splashLineWidth(word) <= MAX_LINE_DOTS) {
      current[current.length - 1] = { ...current[current.length - 1], gapAfter: WORD_GAP };
      current.push(...word);
    } else {
      lines.push([...word]);
    }
  }
  return lines;
}

